version: "3"

services:
  db:
    image: postgres
    container_name: db
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    build: frontend
    env_file: frontend/.env
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: backend
    env_file: backend/.env
    container_name: backend
    hostname: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres:
networks:
  transcendance:
    name: transcendance
    driver: bridge
