version: "3"

services:
  # db:
  #   image: postgres
  #   container_name: db
  #   env_file: .env
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

  frontend:
    build: frontend
    env_file: .env
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "80:80"
    # depends_on:
    #   - db

  # backend:
  #   build:
  #     dockerfile: backend/Dockerfile
  #   env_file: .env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db

volumes:
  postgres:
networks:
  transcendance:
    name: transcendance
    driver: bridge
