version  : "3"

services :

  db:
    image : postgres
    container_name: db
    env_file : .env
    restart : always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
